-- =============================================================================
-- Migration 0003 — competitions (CTFs and cyber competitions)
-- =============================================================================
-- Safe to run on any database created from schema.sql. Idempotent.
-- Run once: Supabase Studio → SQL Editor → paste → Run.
--
-- Same access model as the other public content tables: `anon` may SELECT
-- published rows and nothing else; writes go through the local admin dashboard
-- with the service-role key.
-- =============================================================================

begin;

create table if not exists public.competitions (
  id           bigint generated by default as identity primary key,
  name         text not null,
  organizer    text,
  -- Free-form so it can read naturally: "Jeopardy-style CTF", "Cyber defense".
  format       text not null,
  -- Free-form like experience.period: "2025", "2024 – 2025", "Season 17".
  period       text,
  -- Placement or outcome, e.g. "Top 5% nationally". Empty means not shown.
  result       text,
  team         text,
  description  text not null,
  link         text,
  sort_order   integer not null default 0,
  published    boolean not null default true,
  created_at   timestamptz not null default timezone('utc', now()),
  updated_at   timestamptz not null default timezone('utc', now()),
  -- Rendered as an href: only absolute http(s), which keeps javascript: out.
  constraint competitions_link_scheme check (link is null or link ~* '^https?://'),
  constraint competitions_name_len check (char_length(name) between 1 and 200),
  constraint competitions_description_len check (char_length(description) between 1 and 5000)
);

create unique index if not exists competitions_name_key on public.competitions (name);
create index if not exists competitions_sort_idx on public.competitions (published, sort_order, id);

drop trigger if exists set_updated_at on public.competitions;
create trigger set_updated_at before update on public.competitions
  for each row execute function public.tg_set_updated_at();

alter table public.competitions enable row level security;
alter table public.competitions no force row level security;

drop policy if exists "published competitions are readable" on public.competitions;
create policy "published competitions are readable"
  on public.competitions for select to anon, authenticated
  using (published = true);

revoke all on public.competitions from anon, authenticated;
grant select on public.competitions to anon, authenticated;
grant all on public.competitions to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Starter rows. Results, years and teams are deliberately left empty — fill
-- them in from the admin dashboard (Competitions) rather than here.
insert into public.competitions (name, organizer, format, description, link, sort_order)
values
  ('picoCTF', 'Carnegie Mellon University', 'Jeopardy-style CTF',
   'Carnegie Mellon''s capture-the-flag competition: web exploitation, cryptography, reverse engineering, forensics and binary exploitation challenges.',
   'https://picoctf.org', 10),
  ('Lockheed Martin CYBERQUEST', 'Lockheed Martin', 'Capture the flag',
   'Lockheed Martin''s cyber competition for high school teams, solving security challenges alongside Lockheed Martin cyber professionals.',
   null, 20),
  ('CyberPatriot', 'Air & Space Forces Association', 'Cyber defense',
   'The national youth cyber defense competition: teams find and fix vulnerabilities in Windows and Linux systems under time pressure.',
   'https://www.uscyberpatriot.org', 30)
on conflict (name) do nothing;

commit;
