-- =============================================================================
-- morganbarber.me — complete database schema
-- =============================================================================
-- Idempotent. Safe to run repeatedly on a fresh or existing project.
-- Run with:  psql "$SUPABASE_DB_URL" -f supabase/schema.sql
--        or: paste into Supabase Studio → SQL Editor → Run
--
-- SECURITY MODEL
-- --------------
-- The browser and the Next.js server both authenticate as the `anon` role using
-- the publishable/anon key. That key is public by definition, so `anon` is
-- treated as a hostile identity:
--
--   * Public content tables (blog_posts, projects, experience, education,
--     certifications, competitions) grant `anon` SELECT only, and RLS restricts rows to those
--     explicitly marked published.
--   * Write-heavy tables (analytics, contact_messages, rate_limit_buckets) grant
--     `anon` NOTHING. Writes happen exclusively through SECURITY DEFINER
--     functions that validate, clamp and rate-limit their input. `anon` can
--     never read them back, so the tables cannot be used for exfiltration.
--   * Every SECURITY DEFINER function pins `search_path = ''` and uses fully
--     qualified identifiers, which closes the search_path hijack class of
--     privilege escalation.
--   * RLS is enabled on every table. Bypassing it requires the service-role key,
--     which never reaches the browser and is not needed by this app at all.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 0. Extensions & baseline grants
-- -----------------------------------------------------------------------------

-- gen_random_uuid() is in pg_catalog from PostgreSQL 13 onward, so no extension
-- is required. It is fully qualified everywhere for search_path safety.

-- Start from "deny by default" on the public schema, then grant back explicitly.
revoke all on schema public from public;
grant usage on schema public to anon, authenticated, service_role;

-- Nothing is granted implicitly to future tables; each grant below is deliberate.
alter default privileges in schema public revoke all on tables from anon, authenticated;
-- PostgreSQL grants EXECUTE on new functions to PUBLIC by default; revoke that
-- so every callable function below is an explicit, deliberate grant.
alter default privileges in schema public revoke all on functions from public, anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

-- -----------------------------------------------------------------------------
-- 1. Shared helpers
-- -----------------------------------------------------------------------------

-- Maintains updated_at on any table that has the column.
create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

-- Collapses whitespace, strips C0/C1 control characters, trims and hard-truncates.
-- Used to normalise every piece of untrusted text before it is stored.
create or replace function public.clean_text(value text, max_len integer default 512)
returns text
language sql
immutable
security invoker
set search_path = ''
as $$
  select nullif(
    left(
      btrim(regexp_replace(regexp_replace(value, '[\u0000-\u001F\u007F-\u009F]', ' ', 'g'), '\s+', ' ', 'g')),
      greatest(max_len, 1)
    ),
    ''
  );
$$;

-- -----------------------------------------------------------------------------
-- 2. Content tables
-- -----------------------------------------------------------------------------

create table if not exists public.blog_posts (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  summary     text,
  content     text,
  date        text,
  tag         text,
  published   boolean not null default false,
  reading_minutes integer,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now()),
  constraint blog_posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint blog_posts_title_len check (char_length(title) between 1 and 200),
  constraint blog_posts_summary_len check (summary is null or char_length(summary) <= 1000),
  constraint blog_posts_content_len check (content is null or char_length(content) <= 200000)
);

create table if not exists public.projects (
  id          text primary key,
  title       text not null,
  description text not null,
  category    text not null,
  status      text not null,
  content     text,
  tags        text[] not null default '{}',
  link        text,
  published   boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now()),
  constraint projects_id_format check (id ~ '^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$' and char_length(id) <= 64),
  constraint projects_title_len check (char_length(title) between 1 and 200),
  constraint projects_tags_len check (array_length(tags, 1) is null or array_length(tags, 1) <= 24),
  -- Rendered as an href: only absolute http(s) URLs are ever accepted, which
  -- rules out javascript:, data: and vbscript: payloads at the storage layer.
  constraint projects_link_scheme check (link is null or link ~* '^https?://')
);

create table if not exists public.experience (
  id          bigint generated by default as identity primary key,
  period      text not null,
  role        text not null,
  company     text not null,
  description text not null,
  sort_order  integer not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now())
);

create table if not exists public.education (
  id          bigint generated by default as identity primary key,
  degree      text not null,
  period      text not null,
  school      text not null,
  details     text not null,
  sort_order  integer not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now())
);

create table if not exists public.certifications (
  id          bigint generated by default as identity primary key,
  name        text not null,
  file_url    text not null,
  issuer      text,
  issued_on   date,
  sort_order  integer not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now()),
  -- Same anti-XSS reasoning as projects.link; relative paths are allowed
  -- because certificates are served from our own /public directory.
  constraint certifications_url_scheme check (file_url ~* '^(https?://|/)')
);

-- CTFs and cyber competitions (added in migrations/0003_competitions.sql).
create table if not exists public.competitions (
  id           bigint generated by default as identity primary key,
  name         text not null,
  organizer    text,
  format       text not null,
  period       text,
  result       text,
  team         text,
  description  text not null,
  link         text,
  sort_order   integer not null default 0,
  published    boolean not null default true,
  created_at   timestamptz not null default timezone('utc', now()),
  updated_at   timestamptz not null default timezone('utc', now()),
  constraint competitions_link_scheme check (link is null or link ~* '^https?://'),
  constraint competitions_name_len check (char_length(name) between 1 and 200),
  constraint competitions_description_len check (char_length(description) between 1 and 5000)
);

-- Columns added defensively so the file also upgrades a pre-existing database.
alter table public.blog_posts     add column if not exists published boolean not null default false;
alter table public.blog_posts     add column if not exists reading_minutes integer;
alter table public.blog_posts     add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table public.projects       add column if not exists published boolean not null default false;
alter table public.projects       add column if not exists sort_order integer not null default 0;
alter table public.projects       add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table public.experience     add column if not exists published boolean not null default true;
alter table public.experience     add column if not exists sort_order integer not null default 0;
alter table public.experience     add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table public.education      add column if not exists published boolean not null default true;
alter table public.education      add column if not exists sort_order integer not null default 0;
alter table public.education      add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table public.certifications add column if not exists published boolean not null default true;
alter table public.certifications add column if not exists issuer text;
alter table public.certifications add column if not exists issued_on date;
alter table public.certifications add column if not exists sort_order integer not null default 0;
alter table public.certifications add column if not exists updated_at timestamptz not null default timezone('utc', now());

-- -----------------------------------------------------------------------------
-- 3. Telemetry & messaging tables (no direct anon access)
-- -----------------------------------------------------------------------------

create table if not exists public.analytics (
  id                bigint generated by default as identity primary key,
  path              text not null,
  event_name        text not null default 'page_view',
  session_id        uuid,
  referrer_host     text,
  language          text,
  screen_resolution text,
  device_type       text,
  os                text,
  browser           text,
  geo_country       text,
  geo_region        text,
  geo_city          text,
  -- SHA-256(ip + server-side salt). Never the raw address: the hash supports
  -- unique-visitor counting and abuse throttling without storing a PII value
  -- we would then have to defend.
  visitor_hash      text,
  metadata          jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default timezone('utc', now()),
  constraint analytics_path_len check (char_length(path) between 1 and 512),
  constraint analytics_metadata_size check (octet_length(metadata::text) <= 4096)
);

-- Migrate the original wide-open columns if this is an existing database.
alter table public.analytics add column if not exists event_name text not null default 'page_view';
alter table public.analytics add column if not exists session_id uuid;
alter table public.analytics add column if not exists referrer_host text;
alter table public.analytics add column if not exists device_type text;
alter table public.analytics add column if not exists os text;
alter table public.analytics add column if not exists browser text;
alter table public.analytics add column if not exists geo_country text;
alter table public.analytics add column if not exists geo_region text;
alter table public.analytics add column if not exists geo_city text;
alter table public.analytics add column if not exists visitor_hash text;
alter table public.analytics add column if not exists metadata jsonb not null default '{}'::jsonb;
-- The raw user_agent and full referrer URL are deliberately dropped: the parsed
-- device/os/browser and referrer *host* carry the analytical value without the
-- fingerprinting surface or the query-string secrets referrers often leak.
alter table public.analytics drop column if exists user_agent;
alter table public.analytics drop column if exists referrer;

create table if not exists public.contact_messages (
  id           uuid primary key default pg_catalog.gen_random_uuid(),
  name         text not null,
  email        text,
  message      text not null,
  referrer_host text,
  visitor_hash text,
  status       text not null default 'new',
  created_at   timestamptz not null default timezone('utc', now()),
  constraint contact_name_len check (char_length(name) between 1 and 120),
  constraint contact_message_len check (char_length(message) between 10 and 5000),
  constraint contact_email_format check (email is null or email ~* '^[^@\s]+@[^@\s.]+\.[^@\s]+$'),
  constraint contact_status_valid check (status in ('new', 'read', 'archived', 'spam'))
);

-- Server-side rate limiting. Lives in the database rather than in Next.js memory
-- so the limit holds across serverless instances, restarts and regions.
create table if not exists public.rate_limit_buckets (
  bucket_key   text primary key,
  tokens       integer not null,
  window_start timestamptz not null default timezone('utc', now()),
  updated_at   timestamptz not null default timezone('utc', now())
);

-- -----------------------------------------------------------------------------
-- 4. Indexes
-- -----------------------------------------------------------------------------

create unique index if not exists blog_posts_slug_idx on public.blog_posts (slug);
create index if not exists blog_posts_published_date_idx on public.blog_posts (published, date desc);
create index if not exists projects_published_sort_idx on public.projects (published, sort_order, created_at desc);
create index if not exists experience_sort_idx on public.experience (published, sort_order, id);
create index if not exists education_sort_idx on public.education (published, sort_order, id);
create index if not exists certifications_sort_idx on public.certifications (published, sort_order, id);
create unique index if not exists competitions_name_key on public.competitions (name);
create index if not exists competitions_sort_idx on public.competitions (published, sort_order, id);

create index if not exists analytics_created_at_idx on public.analytics (created_at desc);
create index if not exists analytics_path_created_idx on public.analytics (path, created_at desc);
create index if not exists analytics_session_idx on public.analytics (session_id) where session_id is not null;
create index if not exists analytics_event_idx on public.analytics (event_name, created_at desc);

create index if not exists contact_created_idx on public.contact_messages (created_at desc);
create index if not exists contact_status_idx on public.contact_messages (status, created_at desc);
create index if not exists rate_limit_updated_idx on public.rate_limit_buckets (updated_at);

-- -----------------------------------------------------------------------------
-- 5. updated_at triggers
-- -----------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array['blog_posts', 'projects', 'experience', 'education', 'certifications', 'competitions']
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function public.tg_set_updated_at()', t
    );
  end loop;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Row Level Security
-- -----------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array[
    'blog_posts', 'projects', 'experience', 'education', 'certifications', 'competitions',
    'analytics', 'contact_messages', 'rate_limit_buckets'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    -- NOTE: RLS is enabled but deliberately NOT forced. FORCE would also apply
    -- the policies to the table owner, which would block both the SECURITY
    -- DEFINER write functions in section 8 and ordinary admin seeding, while
    -- protecting against nothing that matters here -- the threat model is a
    -- leaked public anon key, and `anon` is stopped by the combination of
    -- zero table grants (section 7) and zero matching policies below.
    execute format('alter table public.%I no force row level security', t);
  end loop;
end;
$$;

-- Public content: anonymous read of published rows only.
drop policy if exists "published blog posts are readable" on public.blog_posts;
create policy "published blog posts are readable"
  on public.blog_posts for select to anon, authenticated
  using (published = true);

drop policy if exists "published projects are readable" on public.projects;
create policy "published projects are readable"
  on public.projects for select to anon, authenticated
  using (published = true);

drop policy if exists "published experience is readable" on public.experience;
create policy "published experience is readable"
  on public.experience for select to anon, authenticated
  using (published = true);

drop policy if exists "published education is readable" on public.education;
create policy "published education is readable"
  on public.education for select to anon, authenticated
  using (published = true);

drop policy if exists "published certifications are readable" on public.certifications;
create policy "published certifications are readable"
  on public.certifications for select to anon, authenticated
  using (published = true);

drop policy if exists "published competitions are readable" on public.competitions;
create policy "published competitions are readable"
  on public.competitions for select to anon, authenticated
  using (published = true);

-- analytics, contact_messages and rate_limit_buckets intentionally have NO
-- policies for anon/authenticated. With RLS enabled and no matching policy,
-- every direct read and write from the public key is denied. All legitimate
-- access flows through the SECURITY DEFINER functions in section 8, which run
-- as the owner and therefore bypass RLS under controlled conditions.

-- -----------------------------------------------------------------------------
-- 7. Table grants
-- -----------------------------------------------------------------------------

grant select on public.blog_posts, public.projects, public.experience,
                public.education, public.certifications, public.competitions
  to anon, authenticated;

revoke all on public.analytics from anon, authenticated;
revoke all on public.contact_messages from anon, authenticated;
revoke all on public.rate_limit_buckets from anon, authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

-- -----------------------------------------------------------------------------
-- 8. Write paths (SECURITY DEFINER, validated, rate limited)
-- -----------------------------------------------------------------------------

-- Token-bucket limiter. Returns true when the call is allowed.
-- Not exposed to anon directly; only called from the functions below.
create or replace function public.consume_rate_limit(
  p_key       text,
  p_limit     integer,
  p_window    interval
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now      timestamptz := timezone('utc', now());
  v_tokens   integer;
begin
  if p_key is null or p_limit <= 0 then
    return false;
  end if;

  insert into public.rate_limit_buckets as b (bucket_key, tokens, window_start, updated_at)
  values (left(p_key, 200), 1, v_now, v_now)
  on conflict (bucket_key) do update
    set tokens = case
          when b.window_start < v_now - p_window then 1
          else b.tokens + 1
        end,
        window_start = case
          when b.window_start < v_now - p_window then v_now
          else b.window_start
        end,
        updated_at = v_now
  returning b.tokens into v_tokens;

  return v_tokens <= p_limit;
end;
$$;

revoke all on function public.consume_rate_limit(text, integer, interval) from public, anon, authenticated;
revoke all on function public.clean_text(text, integer) from public, anon, authenticated;
revoke all on function public.tg_set_updated_at() from public, anon, authenticated;

-- Records one analytics event. Every field is clamped server-side, so a forged
-- client payload cannot bloat rows or inject oversized values.
create or replace function public.track_event(
  p_path              text,
  p_event_name        text default 'page_view',
  p_session_id        uuid default null,
  p_referrer_host     text default null,
  p_language          text default null,
  p_screen_resolution text default null,
  p_device_type       text default null,
  p_os                text default null,
  p_browser           text default null,
  p_geo_country       text default null,
  p_geo_region        text default null,
  p_geo_city          text default null,
  p_visitor_hash      text default null,
  p_metadata          jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_path     text := public.clean_text(p_path, 512);
  v_event    text := coalesce(public.clean_text(p_event_name, 64), 'page_view');
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
begin
  -- Paths must look like site paths. Anything else is a forged payload.
  if v_path is null or v_path !~ '^/' then
    return;
  end if;

  if jsonb_typeof(v_metadata) <> 'object' or octet_length(v_metadata::text) > 4096 then
    v_metadata := '{}'::jsonb;
  end if;

  -- 240 events per hour per visitor is far above real browsing and far below
  -- what a flood would need to be useful.
  if p_visitor_hash is not null
     and not public.consume_rate_limit('analytics:' || p_visitor_hash, 240, interval '1 hour') then
    return;
  end if;

  insert into public.analytics (
    path, event_name, session_id, referrer_host, language, screen_resolution,
    device_type, os, browser, geo_country, geo_region, geo_city,
    visitor_hash, metadata
  )
  values (
    v_path,
    v_event,
    p_session_id,
    public.clean_text(p_referrer_host, 255),
    public.clean_text(p_language, 35),
    public.clean_text(p_screen_resolution, 24),
    public.clean_text(p_device_type, 32),
    public.clean_text(p_os, 64),
    public.clean_text(p_browser, 64),
    public.clean_text(p_geo_country, 8),
    public.clean_text(p_geo_region, 64),
    public.clean_text(p_geo_city, 96),
    public.clean_text(p_visitor_hash, 64),
    v_metadata
  );
end;
$$;

revoke all on function public.track_event(text, text, uuid, text, text, text, text, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.track_event(text, text, uuid, text, text, text, text, text, text, text, text, text, text, jsonb) to anon, authenticated, service_role;

-- Accepts a contact form submission. Returns a status string rather than raising,
-- so the caller can respond uniformly and never leak which check failed.
create or replace function public.submit_contact_message(
  p_name          text,
  p_message       text,
  p_email         text default null,
  p_referrer_host text default null,
  p_visitor_hash  text default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name    text := public.clean_text(p_name, 120);
  v_email   text := lower(public.clean_text(p_email, 254));
  -- Newlines and tabs survive (messages are multi-line); every other control
  -- character is stripped.
  v_message text := left(
    btrim(regexp_replace(coalesce(p_message, ''),
                         '[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]', '', 'g')),
    5000
  );
begin
  if v_name is null or char_length(v_message) < 10 then
    return 'invalid';
  end if;

  if v_email is not null and v_email !~* '^[^@\s]+@[^@\s.]+\.[^@\s]+$' then
    return 'invalid';
  end if;

  -- 5 messages per visitor per hour.
  if p_visitor_hash is not null
     and not public.consume_rate_limit('contact:' || p_visitor_hash, 5, interval '1 hour') then
    return 'rate_limited';
  end if;

  -- 50 messages site-wide per hour caps the blast radius of a distributed flood.
  if not public.consume_rate_limit('contact:global', 50, interval '1 hour') then
    return 'rate_limited';
  end if;

  insert into public.contact_messages (name, email, message, referrer_host, visitor_hash)
  values (v_name, v_email, v_message, public.clean_text(p_referrer_host, 255), public.clean_text(p_visitor_hash, 64));

  return 'ok';
end;
$$;

revoke all on function public.submit_contact_message(text, text, text, text, text) from public;
grant execute on function public.submit_contact_message(text, text, text, text, text) to anon, authenticated, service_role;

-- Cheap liveness probe that touches the auth path without exposing data.
create or replace function public.health_check()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object('ok', true, 'time', timezone('utc', now()));
$$;

revoke all on function public.health_check() from public;
grant execute on function public.health_check() to anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 9. Retention
-- -----------------------------------------------------------------------------

-- Analytics rows past 180 days have no value and only grow the breach surface.
create or replace function public.prune_old_data()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.analytics
   where created_at < timezone('utc', now()) - interval '180 days';

  delete from public.rate_limit_buckets
   where updated_at < timezone('utc', now()) - interval '2 days';
end;
$$;

revoke all on function public.prune_old_data() from public, anon, authenticated;
grant execute on function public.prune_old_data() to service_role;

-- Schedule it if pg_cron is available (Supabase: Database → Extensions → pg_cron).
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule(
      'prune-old-data',
      '30 3 * * *',
      $cron$select public.prune_old_data();$cron$
    );
  end if;
exception when others then
  raise notice 'pg_cron not scheduled: %', sqlerrm;
end;
$$;

-- -----------------------------------------------------------------------------
-- 10. Resource limits on the public roles
-- -----------------------------------------------------------------------------
-- RLS says which rows the publishable key may see; it says nothing about how
-- many, or for how long a query may run. Without these, `select=*` with no
-- limit returns the whole table, and a pathological filter can hold a
-- connection for as long as Postgres allows.
--
-- PostgREST truncates results above db_max_rows and reports it in Content-Range.
-- statement_timeout cancels the statement without dropping the connection.
-- service_role is left alone: the admin dashboard's aggregation and the
-- retention job legitimately run longer.

alter role anon set pgrst.db_max_rows = '500';
alter role anon set statement_timeout = '5s';
alter role anon set idle_in_transaction_session_timeout = '10s';

alter role authenticated set pgrst.db_max_rows = '1000';
alter role authenticated set statement_timeout = '10s';
alter role authenticated set idle_in_transaction_session_timeout = '30s';

-- The schema layout is free reconnaissance for anyone probing the API.
revoke all on schema information_schema from anon, authenticated;
grant usage on schema information_schema to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 11. Storage: certifications bucket
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('certifications', 'certifications', true, 10485760, array['application/pdf', 'image/png', 'image/jpeg'])
on conflict (id) do update
  set public = true,
      file_size_limit = 10485760,
      allowed_mime_types = array['application/pdf', 'image/png', 'image/jpeg'];

drop policy if exists "certifications are publicly readable" on storage.objects;
create policy "certifications are publicly readable"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'certifications');

-- Uploads stay owner-only: no anon INSERT/UPDATE/DELETE policy is defined.

commit;

-- PostgREST caches role settings; pick up the new limits immediately.
notify pgrst, 'reload config';

-- -----------------------------------------------------------------------------
-- Post-install verification
-- -----------------------------------------------------------------------------
-- select tablename, rowsecurity, relforcerowsecurity
--   from pg_tables t
--   join pg_class c on c.relname = t.tablename
--  where schemaname = 'public';
